#ifndef ALPHA_RING_OFFSET_MCC_H
#define ALPHA_RING_OFFSET_MCC_H

#define OFFSET_MCC_PF_MODULELOAD 0x442394
#define OFFSET_MCC_PF_MODULEUNLOAD 0x4426F8
#define OFFSET_MCC_PF_GAMEINPUT 0x87AB80

#define OFFSET_MCC_PV_WINDOWFOCUSED 0x3CAB860

#define OFFSET_MCC_PF_KEYCHECK 0x88D8CC
#define OFFSET_MCC_PV_KEYBEGIN 0x3F9EB38
#define OFFSET_MCC_PV_KEYEND 0x3F9EB30

#endif //ALPHA_RING_OFFSET_MCC_H
