#ifndef ALPHA_RING_OFFSET_HALOREACH_H
#define ALPHA_RING_OFFSET_HALOREACH_H

#define OFFSET_HALOREACH_PF_ENGINE 0x34818
#define OFFSET_HALOREACH_PF_WORLD 0x575AC
#define OFFSET_HALOREACH_PF_RENDER 0xC3324

#define OFFSET_HALOREACH_PF_ADD_LOCAL_PLAYER 0x43DC8

#define OFFSET_HALOREACH_V_ENTRY_SPLIT_SCREEN 0x2B

#define OFFSET_HALOREACH_V_ENTRY_PLAYERS 0x3

#endif //ALPHA_RING_OFFSET_HALOREACH_H
