#ifndef ALPHA_RING_OFFSET_GROUNDHOG_H
#define ALPHA_RING_OFFSET_GROUNDHOG_H

#define OFFSET_GROUNDHOG_PF_ENGINE 0x613F8
#define OFFSET_GROUNDHOG_PF_WORLD 0x9907C
#define OFFSET_GROUNDHOG_PF_RENDER 0x121F64

#define OFFSET_GROUNDHOG_PF_ADD_LOCAL_PLAYER 0x7C3F8

#define OFFSET_GROUNDHOG_V_ENTRY_PLAYERS 0x1

#endif //ALPHA_RING_OFFSET_GROUNDHOG_H
